name: 'Setup Python Environment'
description: 'Setup Python with caching and essential tools'
inputs:
  python-version:
    description: 'Python version to setup'
    required: true
    default: '3.11'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: 'default'
  install-tox:
    description: 'Whether to install tox'
    required: false
    default: 'false'
  extra-deps:
    description: 'Extra dependencies to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          tox.ini
          requirements*.txt

    - name: Legacy cache step removed
      shell: bash
      run: echo "Cache is now handled by setup-python action"

    - name: Install base tools
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [[ "${{ inputs.install-tox }}" == "true" ]]; then
          pip install tox
        fi
        if [[ -n "${{ inputs.extra-deps }}" ]]; then
          pip install ${{ inputs.extra-deps }}
        fi

    - name: Display Python info
      shell: bash
      run: |
        python --version
        pip --version
        pip list
